name: "Deploy: CI"
on:
  push:
    branches: [ 'main' ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672
    strategy:
      matrix:
        node-version: [ 20.x, 'lts/*' ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install --ignore-scripts
      - name: Run Lint Fix
        run: npm run lint:fix
      - name: Run Unit Tests
        run: npm run test
  Release:
    runs-on: ubuntu-latest
    needs: [ 'Test' ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: NPM Install
        run: npm install --ignore-scripts
      - name: Semantic Release (Dry Run)
        run: npm run semantic-release:dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  Docs:
    runs-on: ubuntu-latest
    needs: [ 'Release' ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: NPM Install
        run: npm install --ignore-scripts
      - name: Generate Typedoc documentation
        run: npm run typedoc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'